feat(push notification carousel): Implement image loading for push notifications - WIP
rees46/rees46-android-sdk pull request #17
Opened 2024-06-04 21:27 UTC by DanielGreenEngineer

Implement image loading for push notifications

2024-06-05 09:33 UTC, TorinAsakura requested changes

2024-06-05 09:33 UTC, TorinAsakura commented on personalizatio-sdk/build.gradle
> +version='1.8.62'
версионный скачок, как у тебя поднялось на несколько десяток ревизий если релизов не было?

2024-06-05 09:33 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/MessagingService.java
> +			SDK.debug("Message Notification Body: " + remoteMessage.getNotification());
эта вещь точно не оносится к задаче, однако она находится в коммите, который гласит "всё сделано!"

2024-06-05 09:33 UTC, TorinAsakura commented on personalizatio-sdk/src/main/java/com/personalizatio/SDK.java
> +			RemoteMessage.Notification notification = remoteMessage.getNotification();
null safety

2024-06-05 20:20 UTC, DanielGreenEngineer commented on personalizatio-sdk/build.gradle
> +version='1.8.62'
Не понял как так вышлл, вернул обратно

2024-06-05 20:20 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/java/com/personalizatio/SDK.java
> +			RemoteMessage.Notification notification = remoteMessage.getNotification();
Согласен, добавил проверки

2024-06-05 20:21 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/rees46/java/com/rees46/sdk/REES46.java
> +                    new AsyncTask<String, Void, Bitmap>() {
Не знал можно ли менять. Заменил на Executor

2024-06-05 20:21 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/rees46/java/com/rees46/sdk/REES46.java
Вынес весь хардкод в константы

2024-06-06 20:48 UTC, TorinAsakura commented
@DanielGreenEngineer обрати внимание на свой ПР
- первое что бросается в глаза это неправильное использование области (scope) который у тебя говорит о месте работы через фразы, а не субъект, ну вот что такое push noitfication carousel? У нас где-то есть такой модуль/файл/метод/событие? И пробелы вообще запрещены в таких местах, разделители должны обрабатываться через спец. символы
- что такое WIP? Ты создаёшь ПР однажды, без возможности менять его имя по ходу работы - тогда зачем ты пишешь WIP? Вместо WIP - используй специальный статус ПРа - draft - находится прямо под блоком ревьюверов в сайдбаре - при условии, что ПР ещё не готов к ревью

2024-06-06 20:48 UTC, TorinAsakura commented
Также, чтобы обратить моё внимание на изменения, которые ты проделал - нужно перезапрашивать ревью - иконка с цикличными стрелками рядом с моим ником в разделе ревьюверов

2024-06-07 07:55 UTC, xeewii commented
@DanielGreenEngineer У нас сейчас происходит миграция на котлин, поэтому есть предложение этот ПР мержить после https://github.com/rees46/rees46-android-sdk/pull/18 соответственно с изменениями уже на котлине

2024-06-07 08:09 UTC, DanielGreenEngineer commented
@xeewii Привет. Логичное предложение, поддерживаю тебя

2024-06-07 12:36 UTC, DanielGreenEngineer commented
**_Первое что бросается в глаза это неправильное использование области (scope) который у тебя говорит о месте работы через фразы, а не субъект, ну вот что такое push noitfication carousel? У нас где-то есть такой модуль/файл/метод/событие? И пробелы вообще запрещены в таких местах, разделители должны обрабатываться через спец. символы_** - Посмотрел пример в одном из риквестов, весомое замечание, исправлюсь. 
 
**_Что такое WIP? Ты создаёшь ПР однажды, без возможности менять его имя по ходу работы - тогда зачем ты пишешь WIP? Вместо WIP - используй специальный статус ПРа - draft - находится прямо под блоком ревьюверов в сайдбаре - при условии, что ПР ещё не готов к ревью_** - Всегда ошибочно считал что так можно помечать риквест в работе, в дальнейшем оставлю себе в использование только draft пометку

**_Также, чтобы обратить моё внимание на изменения, которые ты проделал - нужно перезапрашивать ревью - иконка с цикличными стрелками рядом с моим ником в разделе ревьюверов_** - Не знал об этом, спасибо за совет

2024-06-07 15:32 UTC, xeewii commented
@DanielGreenEngineer Пр с миграцией в мастере, можно менять)

2024-06-07 18:34 UTC, DanielGreenEngineer commented
@xeewii Спасибо большое, затащу себе!)

2024-06-10 13:08 UTC, DanielGreenEngineer commented
@TorinAsakura **Привет. У меня пара вопросов:**
* Заглянул в пайплайны, вижу много фейлов по тестам, стоит ли мне их все починить?
* Нужен твой совет по поводу IntentService, он уже Deprecated, стоит ли его заменить на Worker или же нет?

2024-06-10 19:10 UTC, TorinAsakura commented
> @TorinAsakura **Привет. У меня пара вопросов:**
> 
> * Заглянул в пайплайны, вижу много фейлов по тестам, стоит ли мне их все починить?

- дождись мержа соседнего пра, повтори и если чеки всё ещё падают - давай чинить в отдельной таске, чтобы фичу не тормозить

> * Нужен твой совет по поводу IntentService, он уже Deprecated, стоит ли его заменить на Worker или же нет?
- стоит, но, в отдельной задаче

2024-06-10 19:31 UTC, TorinAsakura commented
@DanielGreenEngineer чекай

2024-06-10 19:33 UTC, DanielGreenEngineer commented
> чекай

Принято

2024-06-11 18:08 UTC, TorinAsakura requested changes

2024-06-11 18:08 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationHelper.kt
> +            /* requestCode = */ System.currentTimeMillis().toInt(),
если я правильно понял реализацию то у тебя requestCode должен быть уникальным для каждого интента, то есть, выходит так, что System.currentTimeMillis вернёт текущий системный час в мс, но, ты же понимаешь, что не во всех случаях этол можеь гарантировать нам уникальность, особенно в кейсах где у нас несколько интентов создаются в один и тот же момент времени?

2024-06-11 18:08 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationHelper.kt
а зачем мне стектрейс? почему не используешь log?

2024-06-12 16:05 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
> +        private const val TITLE_FIELD = "title"
Странное решение, исправил, не заметил в прошлый раз

2024-06-12 16:06 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
>          @Volatile
Заменил волатайл на лейзи инициализацию

2024-06-12 16:06 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
>          @SuppressLint("StaticFieldLeak")
Согласен, исправил благодаря лейзи

2024-06-12 16:07 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
>          private var instance: SDK? = null
С использованием лейзи в этом уже нет необходимости

2024-06-12 16:07 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
>          fun onMessage(remoteMessage: RemoteMessage) {
Согласен, разбил метод на несколько и читаемость стала лучше

2024-06-12 16:08 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationHelper.kt
> +    fun loadBitmaps(urls: String?): List<Bitmap> {
Ты прав!
Заменил на корутины

2024-06-12 16:09 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationHelper.kt
Добавил логирование.

2024-06-12 16:11 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationHelper.kt
> +            /* requestCode = */ System.currentTimeMillis().toInt(),
Да всё верно. Не просчитал этот момент. Добавил атомарный счетчик, считаю, что этого будет достаточно, но если есть предложения, можешь накинуть?

2024-06-12 20:54 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationHelper.kt
> +            /* requestCode = */ System.currentTimeMillis().toInt(),
Лучше использовать уникальные идентификаторы

2024-06-12 20:55 UTC, TorinAsakura commented
@DanielGreenEngineer @xeewii чеки падают, нужно чинить

2024-06-12 20:59 UTC, DanielGreenEngineer commented
> @DanielGreenEngineer @xeewii чеки падают, нужно чинить

Принято, починю

2024-06-12 20:59 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationHelper.kt
> +            /* requestCode = */ System.currentTimeMillis().toInt(),
Хорошо

2024-06-12 21:08 UTC, TorinAsakura requested changes

2024-06-13 10:33 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationHelper.kt
> +            /* requestCode = */ System.currentTimeMillis().toInt(),
Добавил генерацию уникальных значений на основе экшенов, хешкода и текущего индекса изображения

2024-06-13 10:35 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
> +        private fun prepareData(remoteMessage: RemoteMessage): MutableMap<String, String> {
Вынес обработку в отдельный класс, для инкапсуляции работы, а так же провёл глобальный рефактор СДК на предмет кривого нейминга, хардкода и наличия кирилици в описаниях методов

2024-06-13 10:35 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationIntentService.kt
> +class NotificationIntentService : IntentService(TAG) {
Повесил тудуху, задачу создам

2024-06-13 10:35 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationIntentService.kt
> +}
Добавил строки

2024-06-13 12:19 UTC, TorinAsakura approved these changes

2024-06-13 13:38 UTC, TorinAsakura approved these changes

2024-06-13 13:38 UTC, merged