Feat/show story by sdk
rees46/rees46-android-sdk pull request #22
Opened 2024-06-12 12:19 UTC by xeewii

https://github.com/rees46/planning/issues/826

- Добавлено открытие кампании по id
- Добавлен отступ для текста внутри текстового блока
- Исправлен line spacing внутри текстового блока

2024-06-12 12:20 UTC, xeewii commented
@gochicus
Вызов стори кампании через SDK происходит так:
sdk.story(STORY_ID);
где STORY_ID - это числовое (Int) айди кампании

2024-06-12 20:19 UTC, TorinAsakura requested changes

2024-06-12 20:19 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
> +    fun story(storyId: Int) {
мы вроде обсуждали доктрину по которой все новые куски мы пишем начисто без продолжения монолита, а в сдк только инициализацию проводим для доступности. Разве нет?

2024-06-12 20:19 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/listeners/ShowStoryRequestListener.kt
> +internal interface ShowStoryRequestListener {
что такое листинер? можешь кинуть ссылку на паттерн которым ты руководствовалась?

2024-06-12 20:19 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/models/Story.kt
> +    fun resetStartPosition() {
разве это может происходить в модели?

2024-06-12 20:19 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/views/StoriesView.kt
> +    }
объясни конструкцию пожалуйста

2024-06-13 12:17 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
> +    fun story(storyId: Int) {
Вынесла работу со сторисами в отдельный класс

2024-06-13 12:19 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/views/StoriesView.kt
> +    }
Это для оптимизации запроса показа сториса. Если нужный сторис уже загружен, то мы показываем его, вместо того, чтобы делать запрос в сеть

2024-06-13 12:20 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/listeners/ShowStoryRequestListener.kt
> +internal interface ShowStoryRequestListener {
С вынесением работы сторисов в отдельный класс это ушло за ненадобностью

2024-06-13 12:20 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/models/Story.kt
> +    fun resetStartPosition() {
Вернула во вью

2024-06-13 12:25 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
>      fun stories(code: String, listener: OnApiCallbackListener) {
@TorinAsakura не знаю, должен ли этот метод торчать наружу - в документации не описан

2024-06-17 09:54 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
>      fun stories(code: String, listener: OnApiCallbackListener) {
> @TorinAsakura не знаю, должен ли этот метод торчать наружу - в документации не описан

ну так и я не знаю - надо выяснить, если оно никак нас не аффектит - надо выкатываться

2024-06-17 10:25 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/SDK.kt
>      fun stories(code: String, listener: OnApiCallbackListener) {
Это не влияет на работу нашего sdk. Если он нужен пользователю, то может стоит его в документации описать @gochicus

2024-06-17 11:33 UTC, TorinAsakura requested changes
Остались небольшие правки.

В своём коммите я вынес некоторые фичи работы с шрифтами и цветами в отдельный слой. Потом надо будет разделить эти утилиты ещё глубже.

2024-06-17 11:33 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/views/storyItem/TextBlockView.kt
getFontRes и setBackgroundColor вынести наверх

2024-06-17 11:33 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/views/storyItem/TextBlockView.kt
> +    private fun setBackgroundColor(colorString: String, colorOpacity: Int) {
тут внутри какой-то ад происходит, надо упростить этот сеттер да ещё и хардкод внутри

2024-06-17 13:21 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/StoriesManager.kt
> +            //Запоминаем последний клик в сторис, чтобы при вызове события просмотра товара добавить
Почистила кириллицу

2024-06-17 13:21 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/views/storyItem/TextBlockView.kt
Теперь это в TextUtils и ColorUtils соответственно

2024-06-17 13:22 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/views/storyItem/TextBlockView.kt
> +    private fun setBackgroundColor(colorString: String, colorOpacity: Int) {
Сделала метод намного проще

2024-06-17 19:26 UTC, TorinAsakura approved these changes

2024-06-17 19:26 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/views/storyItem/TextBlockView.kt
не-не, там должно быть что-то типа
ui/text/utils.kt | ui/colors/utils.kt, но это не критично, потом вынесешь

2024-06-17 19:29 UTC, TorinAsakura approved these changes

2024-06-17 19:29 UTC, merged