Feat/automate sending mobile push tokens
rees46/rees46-android-sdk pull request #23
Opened 2024-06-13 20:29 UTC by xeewii

https://github.com/rees46/planning/issues/271

2024-06-17 18:49 UTC, TorinAsakura requested changes
я бы также прошёлся по функционалу, тут явно надо поработать над асинхронщиной

2024-06-17 18:49 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +    internal fun initialize(autoSendPushToken: Boolean) {
null safety - нам ведь важно учитывать возможность отсутствия did

2024-06-17 18:49 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +                        val handler = Handler(Looper.getMainLooper())
обработка задач в юай потоке не самая оптимальная вещь

2024-06-17 18:49 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +    private fun init() {
хотелось бы увидеть полноценную обработку ошибок

2024-06-17 18:49 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +        sdk.addToQueue(Thread { this.token })
зачем тут thread?

2024-06-18 08:37 UTC, xeewii commented
> я бы также прошёлся по функционалу, тут явно надо поработать над асинхронщиной

что имеешь в виду именно?
Нет особых мест где это необходимо, а методы связанные с работой апи, под капотом запускаются в отдельном треде

2024-06-18 09:21 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +    internal fun initialize(autoSendPushToken: Boolean) {
Добавила в обработку

2024-06-18 09:21 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +        sdk.addToQueue(Thread { this.token })
Вообще изначально чтобы запрос токена происходил после инициализации, однако переделала то же самое без треда

2024-06-18 09:53 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +    private fun init() {
добавила

2024-06-18 09:54 UTC, TorinAsakura commented
> > я бы также прошёлся по функционалу, тут явно надо поработать над асинхронщиной
> 
> что имеешь в виду именно? Нет особых мест где это необходимо, а методы связанные с работой апи, под капотом запускаются в отдельном треде

это казалось Thread, Handler и Looper - просто месседж писал до того как сел этот кусок разбирать

2024-06-18 10:03 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +                        val handler = Handler(Looper.getMainLooper())
Я ыб сделал как-то так

```kotlin
override fun onError(code: Int, msg: String?) {
                    if (code >= 500 || code <= 0) {
                        Log.e(TAG, "code: $code, $msg")
                        if (attempt < 5) {
                            attempt++
                        }
                        CoroutineScope(Dispatchers.Main).launch {
                            delay(1000L * attempt)
                            init()
                        }
                    }
                }
```

2024-06-18 10:05 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +    private fun init() {
?

2024-06-18 10:44 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +    private fun init() {
кажется я не совсем тебя поняла( Поясни, пожалуйста, что ты здесь имел ввиду

2024-06-18 11:39 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +                        val handler = Handler(Looper.getMainLooper())
Изменила

2024-06-18 16:07 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/RegisterManager.kt
> +                        val handler = Handler(Looper.getMainLooper())
Если делаешь работу с помощью другого участника команды всегда делай [СоКоммитера](https://docs.github.com/ru/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors) - хороший тон.

2024-06-18 16:17 UTC, merged