Refactor: changed deprecated intent service
rees46/rees46-android-sdk pull request #24
Opened 2024-06-14 17:38 UTC by DanielGreenEngineer

https://github.com/rees46/planning/issues/841
Заменён IntentService на BroadcastReceiver позволяющий более гибко управлять действиями из уведомлений и обеспечивает соответствие рекомендациям Android для работы с уведомлениями

2024-06-17 12:40 UTC, TorinAsakura requested changes

2024-06-17 12:40 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationBroadcastReceiver.kt
> +import android.content.BroadcastReceiver
его хорошо использовать для быстрых операций, на долгих задачах он будет почти всегда гарантированно валиться

2024-06-17 12:40 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationBroadcastReceiver.kt
> +            SDK.error("Error caught in load bitmaps", ioException)
вижу что покрыл ты не всё

2024-06-17 12:40 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationBroadcastReceiver.kt
> +}
используй Dispatchers.IO для операций с сетью/IO

2024-06-17 12:40 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationBroadcastReceiver.kt
> +import android.content.BroadcastReceiver
Для длительных тасок используй корутины

2024-06-17 12:40 UTC, TorinAsakura commented on sample/src/rees46/kotlin/com/rees46/sample/SampleApplication.kt
> +            else -> "357382bf66ac0ce2f1722677c59511"
держи это в переменных

2024-06-19 09:45 UTC, DanielGreenEngineer commented on sample/src/rees46/kotlin/com/rees46/sample/SampleApplication.kt
> +            else -> "357382bf66ac0ce2f1722677c59511"
> держи это в переменных

Исправил

2024-06-19 09:48 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationBroadcastReceiver.kt
> +}
> используй Dispatchers.IO для операций с сетью/IO

Добавил Worker для работы и почистил ресивер, что бы он не выполнял эти задачи, а только уведомлял о работе воркер

2024-06-19 09:53 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationBroadcastReceiver.kt
> +            SDK.error("Error caught in load bitmaps", ioException)
> вижу что покрыл ты не всё

Исправил, добавил проверки на неизвестные экшены и проверки на пустые поля

2024-06-19 09:53 UTC, DanielGreenEngineer commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/notification/NotificationBroadcastReceiver.kt
> +import android.content.BroadcastReceiver
> Для длительных тасок используй корутины

Перевёл на воркер, как и хотел ранее

2024-06-20 09:24 UTC, TorinAsakura approved these changes

2024-06-20 09:30 UTC, xeewii approved these changes

2024-06-20 09:34 UTC, merged