Feat/app demo
rees46/rees46-android-sdk pull request #32
Opened 2024-07-03 15:17 UTC by xeewii

https://github.com/rees46/planning/issues/823

Изменены методы для работы с рекомендациями, поиском и трекингом ивентов на более удобные. Текущие помечены как устаревшие

2024-07-09 21:33 UTC, TorinAsakura requested changes
И почему приложение не вынесено отдельно? почему оно всё ещё находится в слое SDK?

2024-07-09 21:33 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/api/managers/RecommendationManager.kt
> +package com.personalizatio.api.managers
Я уже вроде высказывался относительно интерфейсов менеджера, это довольно мусорная абстракция из древнего мира джавы

1.	Избыточная многословность:
Вижу, что у тебя четыре метода getRecommendation и четыре метода getExtendedRecommendation, и они все по сути делают одно и то же. Переопределения с разными параметрами - это не самый элегантный подход.
2.	KISS (Keep It Simple, Stupid):
Давай упростим: один метод для каждого типа рекомендаций и используем дефолтные значения для параметров, где это уместно.
3.	DRY (Don’t Repeat Yourself):
Слишком много повторяющегося кода. Дублирование методов с одинаковой логикой - не лучшая идея.
4.	SOLID - Interface Segregation Principle (ISP):
Интерфейс раздут. Должен ли RecommendationManager заниматься как обычными, так и расширенными рекомендациями? Может быть, стоит разделить это на два интерфейса?
5.	Необоснованное использование колбэков:
Колбэки усложняют код. Почему бы не использовать CompletableFuture или аналогичные механизмы для асинхронного выполнения?

2024-07-09 21:36 UTC, TorinAsakura commented
И как этот пр относится к демо приложению?

2024-07-09 21:41 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/api/managers/RecommendationManager.kt
> +package com.personalizatio.api.managers
@TorinAsakura я только в этом пр'е ввела подобные интерфейсы менеджера, поэтому раньше разговора про это вроде не было. Подскажи, пожалуйста, чем это тогда лучше заменить?

2024-07-10 10:46 UTC, TorinAsakura requested changes

2024-07-10 10:46 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/api/managers/RecommendationManager.kt
> +package com.personalizatio.api.managers
> @TorinAsakura я только в этом пр'е ввела подобные интерфейсы менеджера, поэтому раньше разговора про это вроде не было. Подскажи, пожалуйста, чем это тогда лучше заменить?

## Проблемы:

1.	Большой интерфейс: Интерфейс раздут методами, многие из которых дублируют функциональность с незначительными изменениями.
2.	Нарушение SRP (Single Responsibility Principle): Один интерфейс отвечает за слишком многое. Это делает его изменчивым и трудно тестируемым.
3.	Сложность в поддержке и тестировании: Множество методов с разными параметрами усложняют тестирование и поддержку.

## Решение:

1. Разделение на отдельные интерфейсы

Можно разделить этот интерфейс на несколько, каждое из которых будет отвечать за свою зону ответственности.

2. Использование Use Cases (Interactor-ов)

В гексагональной архитектуре можно выделить отдельные use cases, которые будут инкапсулировать конкретную бизнес-логику.

3. Реализация Use Case

Каждый use case может быть реализован в отдельном классе, что упростит тестирование и поддержку.

4. Инверсия зависимостей

Внедрение зависимостей (Dependency Injection) поможет управлять зависимостями между различными частями системы.

Пример [юзкейсов](https://github.com/rees46/workers/tree/master/contexts/bounce/application-module/src/use-cases) на примере наших новых сервисов

2024-07-11 16:09 UTC, xeewii commented
Замечания будут сделаны в рамках другой задачи:

> 2. Использование Use Cases (Interactor-ов)
> 
> В гексагональной архитектуре можно выделить отдельные use cases, которые будут инкапсулировать конкретную бизнес-логику.
> 
> 3. Реализация Use Case
> 
> Каждый use case может быть реализован в отдельном классе, что упростит тестирование и поддержку.

2024-07-11 16:23 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/api/managers/RecommendationManager.kt
> +package com.personalizatio.api.managers
Убрала лишние методы, оставила необходимые с дефолтными параметрами там, где это необходимо

2024-07-11 16:31 UTC, merged