Feat/integrate di
rees46/rees46-android-sdk pull request #37
Opened 2024-07-16 20:08 UTC by xeewii

https://github.com/rees46/planning/issues/1222

2024-07-23 14:24 UTC, xeewii commented
Здесь я отделила работу с preferences, но не совсем в ней уверена.
1. Ключ для преференсов задает пользователь, то приходится создавать SharedPreferences в sdk и передавать его в data слой через юзкейс и репозиторий - это нормальное решение?
2. Стоит ли всю работу с преференсами отдавать PreferencesDataSource? Или другой data source (например notification) может использовать его, но сам не будет знать ничего об этих сохраняемых данных, как сделано сейчас.

Сомневаюсь в своей реализации насчет этого, поэтому если есть решение лучше, буду рада его узнать)

2024-07-23 18:09 UTC, TorinAsakura commented
> Здесь я отделила работу с preferences, но не совсем в ней уверена.
> 
> 1. Ключ для преференсов задает пользователь, поэтому приходится создавать SharedPreferences в sdk и передавать его в data слой через юзкейс и репозиторий - это нормальное решение?

- Это может нарушать принцип разделения ответственности (SRP) и увеличивать связанность между слоями
> 2. Стоит ли всю работу с преференсами отдавать PreferencesDataSource? Или другой data source (например notification) может использовать его, но сам не будет знать ничего об этих сохраняемых данных, как сделано сейчас.

- Это может усложнить поддержку и тестирование.


## Использование PreferencesDataSource

- Создание отдельного источника данных (DataSource): Это позволит изолировать всю работу с SharedPreferences в одном месте, что упростит поддержку и тестирование.

- Инкапсуляция логики работы с преференсами: Другая логика (например, NotificationDataSource) может использовать PreferencesDataSource для получения необходимых данных, но не будет напрямую работать с SharedPreferences.

## Передача данных через Use Case и репозиторий:

- Передача высокоуровневых данных: Вместо передачи самого объекта SharedPreferences, лучше передавать высокоуровневые данные через use case и репозиторий.

2024-07-23 20:49 UTC, xeewii commented
Спасибо за пояснение!)
Немного поправила по нему и пр готов)

2024-07-23 20:53 UTC, TorinAsakura requested changes

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/models/NotificationSource.kt
> +    val jsonObject: JSONObject
В доменном слое лучше избегать прямого использования классов из Android SDK, таких как JSONObject. Это нарушает принцип чистой архитектуры, где доменный слой должен быть независимым от платформы.

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/models/RecommendedBy.kt
> +    val type: String
type и code открыты для изменения. Лучше использовать val для type и управлять изменением code через методы.

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/models/RecommendedBy.kt
> +    constructor(type: TYPE) {
зачем такой сложный конструктор? Можно ведь сделать проще

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/models/RecommendedBy.kt
> +package com.personalizatio.domain.models
```suggestion
package com.personalizatio.domain.models

data class RecommendedBy(
    val type: TYPE,
    var code: String? = null
) {
    enum class TYPE(val value: String) {
        RECOMMENDATION("dynamic"),
        TRIGGER("chain"),
        BULK("bulk"),
        TRANSACTIONAL("transactional"),
        INSTANT_SEARCH("instant_search"),
        FULL_SEARCH("full_search"),
        STORIES("stories"),
    }
}
```

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/repositories/PreferencesRepository.kt
> +        sharedPreferences: SharedPreferences,
В доменном слое не должно быть упоминания о SharedPreferences. Лучше передавать высокоуровневые данные.

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/repositories/RecommendationRepository.kt
> +interface RecommendationRepository {
stateless must have

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/usecases/notification/GetNotificationSourceUseCase.kt
> +    fun execute(
в котлин принято использовать invoke

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/InitPreferencesUseCase.kt
> +        context: Context,
sharedPreference

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/GetPreferencesValueUseCase.kt
> +class GetPreferencesValueUseCase @Inject constructor(
методы снова не консистентны

2024-07-23 20:53 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/GetPreferencesValueUseCase.kt
> +    fun getSidLastActTime(defaultValue: Long = 0) = preferencesRepository.getSidLastActTime(defaultValue)
например тут должно быть
```suggestion
    fun getSidLastActTime(defaultValue: Long = 0L): Long = preferencesRepository.getSidLastActTime(defaultValue)
```

2024-07-23 21:04 UTC, xeewii commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/InitPreferencesUseCase.kt
> +        context: Context,
Немного не понимаю
Ты пишешь `В доменном слое не должно быть упоминания о SharedPreferences. Лучше передавать высокоуровневые данные.` 
А здесь пишешь, что надо было SharedPreferences передать.
Я здесь циклически запуталась((

2024-07-24 10:31 UTC, xeewii commented on domain/src/main/java/com/personalizatio/domain/models/NotificationSource.kt
> +    val jsonObject: JSONObject
Но ведь org.json.JSONObject не библиотека андроида...

2024-07-24 10:31 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/di/DataSourcesModule.kt
> +    @Singleton
Для PreferencesDataSource точно нужен, в остальных случаях нет - убрала

2024-07-24 10:31 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/di/ModelsModule.kt
> +    @Singleton
Ой, здесь точно не нужен - убрала

2024-07-24 10:57 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/repositories/notification/NotificationDataSource.kt
> +    private fun getTime() = preferencesDataSource.getValue(SOURCE_TIME_KEY, 0)
Да, изменила

2024-07-24 10:57 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/repositories/notification/NotificationRepositoryImpl.kt
> +    private fun isTimeCorrect(time: Long, timeDuration: Int): Boolean {
Изменила, только на 1000 не умножила, ибо там и так миллисекунды

2024-07-24 10:58 UTC, xeewii commented on domain/src/main/java/com/personalizatio/domain/models/RecommendedBy.kt
> +package com.personalizatio.domain.models
И правда прощу и лучше, спасибо! Исправила)

2024-07-24 11:00 UTC, xeewii commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/GetPreferencesValueUseCase.kt
> +    fun getSidLastActTime(defaultValue: Long = 0) = preferencesRepository.getSidLastActTime(defaultValue)
Изменила

2024-07-24 11:09 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/di/RepositoriesModule.kt
> +    abstract fun preferencesRepository(impl: PreferencesRepositoryImpl): PreferencesRepository
Учту, переиминовала

2024-07-24 11:24 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/repositories/recommendation/RecommendationRepositoryImpl.kt
> +    private var recommendedBy: RecommendedBy? = null
Создала RecommendationDataSource и вынесла recommendedBy туда

2024-07-24 11:43 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/mappers/NotificationMapper.kt
> +            jsonObject = JSONObject()
Пока не совсем понимаю куда это вынести, поэтому вернула в то место, где создаются все json'ы. Скорее всего всё то общее создание куда-нибудь вынесу, и уже будет понятнее

2024-07-24 11:43 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/models/NotificationSourceDto.kt
> +    val type: String?,
Убрала nullable

2024-07-24 11:43 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/repositories/notification/NotificationDataSource.kt
> +    private fun getType() = preferencesDataSource.getValue(SOURCE_TYPE_KEY, null)
Заменила на дефолтные значения

2024-07-24 12:13 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/mappers/NotificationMapper.kt
> +    fun toNotificationSource(notificationSourceDto: NotificationSourceDto): NotificationSource {
Убрала nullable поля из NotificationSourceDto, так что тут в принципе все осталось без возможности в null. Или ты что-то другое имеешь в виду?

2024-07-24 12:14 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/repositories/preferences/PreferencesDataSource.kt
> +    private lateinit var sharedPreferences: SharedPreferences
Потому что метод инициализации всё равно зовется во время инициализации сдк.
Но в целом это не очень верно, убрала)

2024-07-24 12:15 UTC, xeewii commented on data/src/main/java/com/personalizatio/data/repositories/preferences/PreferencesDataSource.kt
> +    internal fun<T> saveValue(field: String, value: T) =
Да, сохранятся только те, что могут сохраниться (when внутри метода).
Или стоит написать отдельные функции для каждого возможного типа?

2024-07-24 12:20 UTC, xeewii commented on domain/src/main/java/com/personalizatio/domain/repositories/RecommendationRepository.kt
> +interface RecommendationRepository {
Создала RecommendationDataSource для данных

2024-07-24 12:23 UTC, xeewii commented on domain/src/main/java/com/personalizatio/domain/usecases/notification/GetNotificationSourceUseCase.kt
> +    fun execute(
Переименовала

2024-07-24 12:35 UTC, xeewii commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/GetPreferencesValueUseCase.kt
> +class GetPreferencesValueUseCase @Inject constructor(
Не совсем поняла как тут правильно назвать... get + название нужного значения

2024-07-24 15:36 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/GetPreferencesValueUseCase.kt
> +class GetPreferencesValueUseCase @Inject constructor(
к консистентности также относится типизация и остальная начинка, она должна быть единообразной

2024-07-24 15:41 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/InitPreferencesUseCase.kt
> +        context: Context,
Не-не-не, погоди, тут что-то не так, тут ведь другой был код, ничего не понимаю:

Вот код который был тут в момент моего первого ревью:
```kotlin
package com.personalizatio.domain.usecases.preferences

import android.content.SharedPreferences
import com.personalizatio.domain.repositories.PreferencesRepository
import javax.inject.Inject

class InitPreferencesUseCase @Inject constructor(
    private val preferencesRepository: PreferencesRepository
) {

    fun execute(
        sharedPreferences: SharedPreferences,
        preferencesKey: String
    ) {
        preferencesRepository.initialize(
            sharedPreferences = sharedPreferences,
            preferencesKey = preferencesKey
        )
    }
}
```

wtf?

2024-07-24 15:42 UTC, TorinAsakura requested changes
Надо разобраться с оставшимися артефактами

2024-07-24 15:44 UTC, xeewii commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/InitPreferencesUseCase.kt
> +        context: Context,
Верно, был такой.
Но ты написал, что не нужно передавать SharedPreferences, вот я и изменила.
Но, кажется, не так изменила?)

2024-07-24 15:47 UTC, TorinAsakura commented on data/src/main/java/com/personalizatio/data/mappers/NotificationMapper.kt
> +            jsonObject = JSONObject()
Это должно было выглядеть примерно следующим образом

```kotlin
       return NotificationSource(
            jsonObject = JSONObject().apply {
                put("from", type)
                put("code", id)
            }
        )
```

2024-07-24 15:48 UTC, xeewii commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/GetPreferencesValueUseCase.kt
> +class GetPreferencesValueUseCase @Inject constructor(
Да вроде всё единообразно...
Или ты имеешь в виду называть `getPreferences + название`?
Или чего не понимаю?;

2024-07-24 15:48 UTC, TorinAsakura commented on data/src/main/java/com/personalizatio/data/repositories/preferences/PreferencesDataSource.kt
> +    internal fun<T> saveValue(field: String, value: T) =
Конечно стоит

2024-07-24 15:52 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/models/NotificationSource.kt
> +    val jsonObject: JSONObject
чот ересь какая-то, тут же был другой импорт…

2024-07-24 15:52 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/models/NotificationSource.kt
> +    val jsonObject: JSONObject
да даже если это не дройдСДК - таких вещей в доменном слое всё равно быть не должно

2024-07-25 10:48 UTC, xeewii commented
> Надо разобраться с оставшимися артефактами

@TorinAsakuraПереспросила насчет пары замечаний, чтобы правильнее их понять)

2024-07-25 15:27 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/GetPreferencesValueUseCase.kt
> +class GetPreferencesValueUseCase @Inject constructor(
верно

2024-07-25 15:28 UTC, TorinAsakura commented on domain/src/main/java/com/personalizatio/domain/usecases/preferences/InitPreferencesUseCase.kt
> +        context: Context,
> Верно, был такой. Но ты написал, что не нужно передавать SharedPreferences, вот я и изменила на context. И запуталась, как в итоге надо?)

сделала правильно, но, я-то тебе писал замечание на старый код, крч не суть, сделано правильно, не понятно что не понятно

2024-07-25 15:30 UTC, TorinAsakura approved these changes

2024-07-25 15:31 UTC, merged