Feat/close story by button click
rees46/rees46-android-sdk pull request #38
Opened 2024-07-19 17:00 UTC by xeewii

https://github.com/rees46/planning/issues/1227

- Сделала закрытие сторисов при нажатии на кнопку.
- Небольшой рефакторинг, чтобы в часть внутренних элементы StoriesView не приходилось передавать сам StoriesView, а только необходимые части.

2024-07-22 15:35 UTC, TorinAsakura requested changes

2024-07-22 15:35 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/StoryState.kt
> +}
последняя строка

story.enum.kt - мы используем конвенциональные именования файлов с использованием суффиксов

например - https://github.com/rees46/rees46-js-sdk/tree/master/v3/src/constants
также можешь глянуть на уровень выше

2024-07-22 16:06 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/StoryState.kt
> +}
Глупый вопрос, но мне нужно разъяснить...
Я же правильно понимаю, что это просто пример?
Потому что это же не очень подходит для именований android.
То есть я адаптирую и называю StoryStateEnum.kt?

2024-07-22 17:25 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/StoryState.kt
> +}
> Глупый вопрос, но мне нужно разъяснить... Я же правильно понимаю, что это просто пример? Потому что это же не очень подходит для именований android. То есть я адаптирую и называю StoryStateEnum.kt?

почему не подходит? где-то есть запрет на конвеционалки?

2024-07-22 17:31 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/StoryState.kt
> +}
Просто это кажется выбивающимся из общей стилистики наименований, то есть то, что файл с маленькой буквы и с точкой в качестве разделителя.

И ты имеешь в виду, что в нём должны храниться все енамы, относящиеся к сторисам?
Или для каждого свой? В таком случая я бы назвала story-state.enum.kt или storyState.enum.kt хотя бы, а то мало ли какие там ещё енамы могут появиться)

2024-07-22 17:55 UTC, TorinAsakura commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/StoryState.kt
> +}
> Потому что это кажется выбивающимся из общей стилистики наименований, то есть то, что файл с маленькой буквы и с точкой в качестве разделителя.
> 
> И ты имеешь в виду, что в нём должны храниться все енамы, относящиеся к сторисам? Или для каждого свой файл? В таком случая я бы назвала story-state.enum.kt или storyState.enum.kt хотя бы, а то мало ли какие там ещё енамы могут появиться)

верно, так и должно быть и да, ты всё верно поняла

2024-07-22 20:23 UTC, xeewii commented on personalizatio-sdk/src/main/kotlin/com/personalizatio/stories/StoryState.kt
> +}
Изменила)
Но была бы очень благодарна, если бы ты чуть конкретнее написал, что я правильно поняла, потому что я тут три варианта предложила и конкретно могла не так поняла, какой из них правильный в итоге)

2024-07-23 16:32 UTC, TorinAsakura approved these changes

2024-07-23 16:35 UTC, merged